#!/bin/sh
#
# From the Funko Digital team!
#
# Ensure commits are prefixed with ticket numbers
# or are merge commits.
#
# To install:
#
# mkdir -p ~/.git-templates/hooks/
# git config --global init.templatedir '~/.git-templates'
# (cd ~/.git-templates/hooks/ && curl -O https://gist.githubusercontent.com/ryanpcmcquen/d0f0a265dde5cfdbd8b49d126083da6a/raw/commit-msg)
# chmod +x ~/.git-templates/hooks/commit-msg
#
# Then re-initialize all your git repos.
# If your repos are all in one directory,
# `cd` to that directory and run this to
# re-initialize all of them:
#
# for DIR in $(find . -type d -maxdepth 1); do (cd $DIR && echo $DIR && git init); done
#
# --------------------------------------------------------
#
# To reinstall this script, download the latest version:
#
# (cd ~/.git-templates/hooks/ && curl -O https://gist.githubusercontent.com/ryanpcmcquen/d0f0a265dde5cfdbd8b49d126083da6a/raw/commit-msg)
# chmod +x ~/.git-templates/hooks/commit-msg
#
# Then `cd` to the directory with all your repos,
# and run:
#
# for DIR in $(find . -type d -maxdepth 1); do (echo $DIR && cd $DIR/.git/hooks && cp ~/.git-templates/hooks/commit-msg . && chmod +x commit-msg); done
#

MSG=$(sed "/^#/d" "$1")
VALID_TICKET_PREFIX=$(echo "$MSG" | egrep "[A-Z]{2,9}-\\d+:?\\s.*")
MERGE_BRANCH_SYNTAX=$(echo "$MSG" | grep "^Merge")

if [ -z "${VALID_TICKET_PREFIX}" ] && [ -z "${MERGE_BRANCH_SYNTAX}" ]; then
    echo
    echo " _____                    _ "
    echo "|  ___|                  | |"
    echo "| |__ _ __ _ __ ___  _ __| |"
    echo "|  __| '__| '__/ _ \| '__| |"
    echo "| |__| |  | | | (_) | |  |_|"
    echo "\____/_|  |_|  \___/|_|  (_)"
    echo
    echo "Message is not prefixed with ticket number and is not a merge."
    echo
    exit 1
fi
