#!/usr/bin/env python3
'''
A super simple password generator.
'''
import string
import random

reasonableCharacters = (
    string.digits + string.ascii_letters + string.punctuation
)


def password(minimum=40, maximum=50):
    return ''.join(
        random.choice(reasonableCharacters) for x in range(
            random.randint(minimum, maximum)
        )
    )

print(password())
