#!/bin/sh
## sudo wget -N https://gist.githubusercontent.com/ryanpcmcquen/e0722b0bb94d347171c4/raw/lwp -P /usr/local/bin; sudo chmod 755 /usr/local/bin/lwp
## easy shortcut to lftp in to wpengine stuff
if [ -z `echo "${@}" | grep -i staging` ]; then
  echo "You will run: lftp -e \"set sftp:auto-confirm yes;\" sftp://"${@}"@"${@}".wpengine.com:2222"
  lftp -e "set sftp:auto-confirm yes;" sftp://"${@}"@"${@}".wpengine.com:2222
else
  echo "You will run: lftp -e \"set sftp:auto-confirm yes;\" sftp://"${@}"@"`echo "${@}" | sed 's/-/./g'`".wpengine.com:2222"
  lftp -e "set sftp:auto-confirm yes;" sftp://"${@}"@"`echo \"${@}\" | sed 's/-/./g'`".wpengine.com:2222
fi